const safeText = value => String(value ?? '');
async function getLibraryItems(root) {
  const backend = window.WedaBackend;
  if (!backend?.ready) { const response = await fetch(`${root.dataset.library}?v=${Date.now()}`, { cache: 'no-store' }); if (!response.ok) throw new Error(`Metadata request failed (${response.status})`); return response.json(); }
  const kind = root.dataset.library.includes('presentations') ? 'presentations' : 'documents';
  const { data, error } = await backend.client.from('library_items').select('*').eq('kind', kind).eq('is_public', true).order('created_at', { ascending: false });
  if (error) throw error;
  return Promise.all(data.map(async item => { const { data: signed } = await backend.client.storage.from('research-assets').createSignedUrl(item.storage_path, 3600); return {...item,status:'available',approved:true,date:item.created_at?new Date(item.created_at).toLocaleDateString():null,type:item.mime_type==='application/pdf'?'PDF':'PowerPoint',size:item.size_bytes?`${(item.size_bytes/1048576).toFixed(1)} MB`:null,viewUrl:signed?.signedUrl||null,downloadUrl:signed?.signedUrl?`${signed.signedUrl}&download=${encodeURIComponent(item.title)}`:null}; }));
}
function buildCard(item) {
  const article=document.createElement('article'); article.className='card reveal is-visible'; const heading=document.createElement('h2'); heading.textContent=safeText(item.title); const desc=document.createElement('p'); desc.textContent=safeText(item.description); const meta=document.createElement('div'); meta.className='meta';
  [item.category,item.status==='available'?'Available':'Coming soon',item.version,item.type,item.size,item.date].filter(Boolean).forEach((value,index)=>{const span=document.createElement('span');span.className=`badge ${index===1?item.status:''}`;span.textContent=safeText(value);meta.append(span)});
  const actions=document.createElement('div');actions.className='actions'; if(item.status==='available'&&item.approved&&item.viewUrl){const view=document.createElement('a');view.className='button';view.href=item.viewUrl;view.target='_blank';view.rel='noopener noreferrer';view.textContent='View';actions.append(view)} if(item.status==='available'&&item.approved&&item.downloadUrl){const download=document.createElement('a');download.className='button button-secondary';download.href=item.downloadUrl;download.textContent='Download';actions.append(download)} if(!actions.children.length){const unavailable=document.createElement('span');unavailable.className='button button-disabled';unavailable.setAttribute('aria-disabled','true');unavailable.textContent='Coming soon';actions.append(unavailable)} article.append(heading,meta,desc,actions);return article;
}
async function loadLibrary(){const root=document.querySelector('[data-library]');if(!root)return;const list=document.querySelector('#library-list');const count=document.querySelector('#result-count');try{const items=await getLibraryItems(root);const search=document.querySelector('#library-search');const category=document.querySelector('#category-filter');const status=document.querySelector('#status-filter');[...new Set(items.map(x=>x.category))].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;category.append(option)});const requestedCategory=new URLSearchParams(location.search).get('category');if(requestedCategory&&[...category.options].some(option=>option.value===requestedCategory)){category.value=requestedCategory}function render(){const query=search.value.trim().toLowerCase();const filtered=items.filter(item=>(!query||`${item.title} ${item.description} ${item.category}`.toLowerCase().includes(query))&&(!category.value||item.category===category.value)&&(!status.value||item.status===status.value));list.replaceChildren();count.textContent=`${filtered.length} item${filtered.length===1?'':'s'}${category.value?` in ${category.value}`:''}`;if(!filtered.length){const empty=document.createElement('p');empty.className='library-empty';empty.textContent='No documents have been added to this category yet.';list.append(empty);return}filtered.forEach(item=>list.append(buildCard(item)))}[search,category,status].forEach(control=>control.addEventListener(control===search?'input':'change',render));render()}catch(error){list.replaceChildren();const message=document.createElement('div');message.className='notice notice-warning';message.innerHTML='<strong>Library unavailable.</strong><br>The catalogue could not be loaded. Please try again later.';list.append(message);count.textContent='Unavailable';console.error(error)}}
loadLibrary();
